### ISSUE TITLE
genome provenance

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenie#81]
Problem: two users may use the string 'hg38' to refer to 2 different things. we should allow unique identifiers to disambiguate.

Assume first we have a way of assigning a unique identifier that unambiguously defines each genome. Two approach options. First, add a `genome_aliases` section to the config that maps human-readable strings to unique identifiers

```
genome_aliases:
  hg38: "64821b23d7a3c6bf42b697de48898110"
  mm10: "a6a8c22f0d0849d43c105f4d242fa62b"

genomes:
  64821b23d7a3c6bf42b697de48898110:
    description: blah blah blah
    assets:
      bowtie2_index
```

Or, just add the checksum as an attribute under a human-readable genome in the current format:

```
genomes:
  hg38:
    checksum: 64821b23d7a3c6bf42b697de48898110
    description: blah blah blah
    assets:
      bowtie2_index
```

Now, to use this collection-level checksum: If your local genome has a checksum attribute, then the `pull` command will check the local genome checksum vs the server checksum for that same human-readable identifier. If they don't match, then you may not want to pull references for that name because they were built with a different input sequence than you have.

If the server does have an asset that matches your genome's checksum, it could return that instead, with a warning. This basically indicates that you and the server refer to the same genome with different human-readable keys, which isn't a major problem.

What about for assets that aren't tied to a genome, really, but are just using the refgenie infrastructure? Well... I don't think such assets exist, but if a genome lacks a 'checksum', (either on the server or local) then it just doesn't do the check. For our server I think we make sure all genomes have checksums.

## How to inject the unique identifier into the config?

For this to work, the local genomes folder needs an identifier for each genome. Where should it come from? Well, we could require that you must first build the fasta asset. This establishes which genome you are going to use, the checksum can be calculated and recorded, and links it to your human-readable identifier. But could you want to establish a genome without building fasta? Yes, sure; on a server where we just need an index but not the whole sequence. You might not need the fasta asset, but could pull just the bowtie2-indexes for example. So we need a new command to establish a genome identity for this case. Something like...

To set a genome alias locally, using your own checksum manually (that you'd have to look up somewhere)
```
refgenie alias -g hg38 --checksum 64821b23d7a3c6bf42b697de48898110
```
Or to use a checksum straight from the server

```
refgenie alias -g hg38
```

This would also happen automatically on first pull, if the genome hasn't been initialized, syncing the identity with the server. All these do is add to the config file:

```
genomes:
  hg38:
    checksum: 64821b23d7a3c6bf42b697de48898110
    description: blah blah blah
```

Now, when you `pull -g hg38 ...` it checks that checksum.
